import type { Activity, BookingPlatform } from '../types';

// ─── Booking Platforms ─────────────────────────────────────────────────────────

export const BOOKING_PLATFORMS: Record<string, BookingPlatform> = {
  opentable: { name: 'OpenTable', url: 'https://www.opentable.com', logo: '🍽️', category: 'restaurant' },
  resy: { name: 'Resy', url: 'https://resy.com', logo: '🪑', category: 'restaurant' },
  yelp: { name: 'Yelp', url: 'https://www.yelp.com', logo: '⭐', category: 'restaurant' },
  bookingcom: { name: 'Booking.com', url: 'https://www.booking.com', logo: '🏨', category: 'hotel' },
  airbnb: { name: 'Airbnb', url: 'https://www.airbnb.com', logo: '🏠', category: 'hotel' },
  agoda: { name: 'Agoda', url: 'https://www.agoda.com', logo: '🌏', category: 'hotel' },
  getyourguide: { name: 'GetYourGuide', url: 'https://www.getyourguide.com', logo: '🎟️', category: 'activity' },
  viator: { name: 'Viator', url: 'https://www.viator.com', logo: '🗺️', category: 'activity' },
  klook: { name: 'Klook', url: 'https://www.klook.com', logo: '🎪', category: 'activity' },
  skyscanner: { name: 'Skyscanner', url: 'https://www.skyscanner.com', logo: '✈️', category: 'transport' },
};

// ─── Mock Places by City ───────────────────────────────────────────────────────

export const MOCK_PLACES: Record<string, Activity[]> = {
  'Paris': [
    {
      id: 'paris-1', name: 'Eiffel Tower', type: 'attraction', category: 'tourist',
      description: 'The iconic iron lattice tower on the Champ de Mars, the symbol of Paris and France.',
      address: 'Champ de Mars, 5 Avenue Anatole France, 75007 Paris',
      lat: 48.8584, lng: 2.2945, durationMin: 90, distanceFromPrevKm: 0, travelTimeMin: 0,
      rating: 4.7, reviewCount: 234521, photos: [], openingHours: '9:00 AM - 11:45 PM',
      priceLevel: 2, requiresBooking: true,
      bookingPlatforms: [BOOKING_PLATFORMS.getyourguide, BOOKING_PLATFORMS.viator],
      tags: ['iconic', 'views', 'romantic', 'landmark'], isEssential: false,
    },
    {
      id: 'paris-2', name: 'Louvre Museum', type: 'museum', category: 'culture',
      description: 'The world\'s largest art museum and historic monument, home to the Mona Lisa.',
      address: 'Rue de Rivoli, 75001 Paris',
      lat: 48.8606, lng: 2.3376, durationMin: 180, distanceFromPrevKm: 2.8, travelTimeMin: 15,
      rating: 4.7, reviewCount: 189432, photos: [], openingHours: '9:00 AM - 6:00 PM (Closed Tue)',
      priceLevel: 2, requiresBooking: true,
      bookingPlatforms: [BOOKING_PLATFORMS.getyourguide, BOOKING_PLATFORMS.klook],
      tags: ['art', 'history', 'culture', 'world-famous'], isEssential: false,
    },
    {
      id: 'paris-3', name: 'Le Marais District', type: 'attraction', category: 'local_life',
      description: 'Historic neighbourhood with trendy boutiques, art galleries, and great cafés.',
      address: 'Le Marais, 75003 Paris',
      lat: 48.8557, lng: 2.3520, durationMin: 120, distanceFromPrevKm: 1.5, travelTimeMin: 10,
      rating: 4.5, reviewCount: 45230, photos: [], openingHours: 'Open 24 hours',
      priceLevel: 1, requiresBooking: false,
      bookingPlatforms: [], tags: ['shopping', 'art', 'trendy', 'neighbourhood'], isEssential: false,
    },
    {
      id: 'paris-4', name: 'Café de Flore', type: 'cafe', category: 'food',
      description: 'Historic Parisian café frequented by philosophers and celebrities since the 1880s.',
      address: '172 Boulevard Saint-Germain, 75006 Paris',
      lat: 48.8540, lng: 2.3328, durationMin: 60, distanceFromPrevKm: 1.2, travelTimeMin: 8,
      rating: 4.2, reviewCount: 12450, photos: [], openingHours: '7:30 AM - 1:30 AM',
      priceLevel: 2, requiresBooking: false,
      bookingPlatforms: [BOOKING_PLATFORMS.resy], tags: ['coffee', 'historic', 'iconic', 'brunch'], isEssential: false,
    },
    {
      id: 'paris-5', name: 'Notre-Dame Cathedral', type: 'historical', category: 'culture',
      description: 'Medieval Catholic cathedral on the Île de la Cité, a masterpiece of French Gothic architecture.',
      address: '6 Parvis Notre-Dame, 75004 Paris',
      lat: 48.8530, lng: 2.3499, durationMin: 60, distanceFromPrevKm: 0.9, travelTimeMin: 6,
      rating: 4.7, reviewCount: 98230, photos: [], openingHours: '8:00 AM - 6:45 PM',
      priceLevel: 0, requiresBooking: false,
      bookingPlatforms: [], tags: ['gothic', 'historic', 'free', 'landmark'], isEssential: false,
    },
    {
      id: 'paris-6', name: 'Montmartre & Sacré-Cœur', type: 'attraction', category: 'tourist',
      description: 'Bohemian hilltop neighbourhood with panoramic views of Paris and the stunning white basilica.',
      address: '35 Rue du Chevalier de la Barre, 75018 Paris',
      lat: 48.8867, lng: 2.3431, durationMin: 120, distanceFromPrevKm: 4.1, travelTimeMin: 20,
      rating: 4.7, reviewCount: 143210, photos: [], openingHours: '6:00 AM - 10:30 PM',
      priceLevel: 0, requiresBooking: false,
      bookingPlatforms: [], tags: ['views', 'art', 'bohemian', 'free'], isEssential: false,
    },
    {
      id: 'paris-7', name: 'Le Comptoir du Relais', type: 'restaurant', category: 'food',
      description: 'Classic Parisian brasserie known for its charcuterie, great wine, and authentic bistro atmosphere.',
      address: '9 Carrefour de l\'Odéon, 75006 Paris',
      lat: 48.8517, lng: 2.3393, durationMin: 90, distanceFromPrevKm: 1.8, travelTimeMin: 12,
      rating: 4.4, reviewCount: 8920, photos: [], openingHours: '9:00 AM - 11:00 PM',
      priceLevel: 2, requiresBooking: true,
      bookingPlatforms: [BOOKING_PLATFORMS.resy, BOOKING_PLATFORMS.opentable], tags: ['french', 'bistro', 'wine', 'authentic'], isEssential: false,
    },
    {
      id: 'paris-8', name: 'Galeries Lafayette', type: 'shopping', category: 'shopping',
      description: 'Iconic French department store with an extraordinary Art Nouveau glass dome and luxury brands.',
      address: '40 Boulevard Haussmann, 75009 Paris',
      lat: 48.8735, lng: 2.3323, durationMin: 90, distanceFromPrevKm: 2.3, travelTimeMin: 15,
      rating: 4.4, reviewCount: 67830, photos: [], openingHours: '9:30 AM - 9:30 PM',
      priceLevel: 3, requiresBooking: false,
      bookingPlatforms: [], tags: ['luxury', 'fashion', 'department store', 'architecture'], isEssential: false,
    },
    {
      id: 'paris-9', name: 'Moulin Rouge', type: 'nightclub', category: 'nightlife',
      description: 'The world\'s most famous cabaret, home of the French Can-Can since 1889.',
      address: '82 Boulevard de Clichy, 75018 Paris',
      lat: 48.8842, lng: 2.3323, durationMin: 150, distanceFromPrevKm: 3.2, travelTimeMin: 18,
      rating: 4.5, reviewCount: 32140, photos: [], openingHours: 'Shows at 9:00 PM & 11:00 PM',
      priceLevel: 4, requiresBooking: true,
      bookingPlatforms: [BOOKING_PLATFORMS.getyourguide, BOOKING_PLATFORMS.viator, BOOKING_PLATFORMS.klook], tags: ['cabaret', 'show', 'iconic', 'nightlife'], isEssential: false,
    },
    {
      id: 'paris-10', name: 'Musée d\'Orsay', type: 'museum', category: 'culture',
      description: 'Impressionist and post-impressionist masterpieces in a stunning converted railway station.',
      address: '1 Rue de la Légion d\'Honneur, 75007 Paris',
      lat: 48.8600, lng: 2.3266, durationMin: 120, distanceFromPrevKm: 1.4, travelTimeMin: 9,
      rating: 4.7, reviewCount: 112340, photos: [], openingHours: '9:30 AM - 6:00 PM (Closed Mon)',
      priceLevel: 2, requiresBooking: true,
      bookingPlatforms: [BOOKING_PLATFORMS.klook, BOOKING_PLATFORMS.getyourguide], tags: ['impressionism', 'Monet', 'van Gogh', 'art'], isEssential: false,
    },
    {
      id: 'paris-11', name: 'Luxembourg Gardens', type: 'park', category: 'outdoor',
      description: 'Beautiful 23-hectare garden with fountains, sculptures, and the Palais du Luxembourg.',
      address: 'Jardin du Luxembourg, 75006 Paris',
      lat: 48.8462, lng: 2.3372, durationMin: 60, distanceFromPrevKm: 1.0, travelTimeMin: 7,
      rating: 4.7, reviewCount: 87650, photos: [], openingHours: '7:30 AM - dusk',
      priceLevel: 0, requiresBooking: false,
      bookingPlatforms: [], tags: ['free', 'peaceful', 'gardens', 'picnic'], isEssential: false,
    },
    {
      id: 'paris-12', name: 'American Hospital of Paris', type: 'essential', category: 'essential',
      description: 'International-standard hospital with English-speaking doctors.',
      address: '63 Boulevard Victor Hugo, 92200 Neuilly-sur-Seine',
      lat: 48.8888, lng: 2.2659, durationMin: 0, distanceFromPrevKm: 0, travelTimeMin: 0,
      rating: 4.2, reviewCount: 1230, photos: [], openingHours: '24 hours',
      priceLevel: 0, requiresBooking: false,
      bookingPlatforms: [], tags: ['emergency', 'medical', 'english'], isEssential: true,
    },
  ],

  'Tokyo': [
    {
      id: 'tokyo-1', name: 'Senso-ji Temple', type: 'historical', category: 'culture',
      description: 'Tokyo\'s oldest Buddhist temple in Asakusa, famous for its Kaminarimon thunder gate.',
      address: '2 Chome-3-1 Asakusa, Taito City, Tokyo',
      lat: 35.7148, lng: 139.7967, durationMin: 90, distanceFromPrevKm: 0, travelTimeMin: 0,
      rating: 4.7, reviewCount: 198430, photos: [], openingHours: '6:00 AM - 5:00 PM',
      priceLevel: 0, requiresBooking: false,
      bookingPlatforms: [], tags: ['temple', 'historic', 'free', 'cultural'], isEssential: false,
    },
    {
      id: 'tokyo-2', name: 'Shibuya Crossing', type: 'attraction', category: 'tourist',
      description: 'The world\'s busiest pedestrian crossing — a true Tokyo experience.',
      address: 'Shibuya, Tokyo',
      lat: 35.6595, lng: 139.7004, durationMin: 30, distanceFromPrevKm: 6.8, travelTimeMin: 25,
      rating: 4.6, reviewCount: 156780, photos: [], openingHours: '24 hours',
      priceLevel: 0, requiresBooking: false,
      bookingPlatforms: [], tags: ['iconic', 'free', 'photography', 'city'], isEssential: false,
    },
    {
      id: 'tokyo-3', name: 'Tsukiji Outer Market', type: 'attraction', category: 'food',
      description: 'Vibrant street food market with the freshest sushi, seafood, and Japanese snacks.',
      address: '4 Chome-16-2 Tsukiji, Chuo City, Tokyo',
      lat: 35.6654, lng: 139.7707, durationMin: 90, distanceFromPrevKm: 3.1, travelTimeMin: 18,
      rating: 4.5, reviewCount: 67234, photos: [], openingHours: '5:00 AM - 2:00 PM',
      priceLevel: 1, requiresBooking: false,
      bookingPlatforms: [BOOKING_PLATFORMS.klook], tags: ['sushi', 'seafood', 'market', 'food tour'], isEssential: false,
    },
    {
      id: 'tokyo-4', name: 'teamLab Borderless', type: 'entertainment', category: 'culture',
      description: 'Immersive digital art museum with stunning interactive light installations.',
      address: '1-3-8 Ariake, Koto City, Tokyo',
      lat: 35.6295, lng: 139.7843, durationMin: 150, distanceFromPrevKm: 4.2, travelTimeMin: 22,
      rating: 4.8, reviewCount: 45632, photos: [], openingHours: '10:00 AM - 9:00 PM',
      priceLevel: 2, requiresBooking: true,
      bookingPlatforms: [BOOKING_PLATFORMS.klook, BOOKING_PLATFORMS.getyourguide], tags: ['digital art', 'immersive', 'instagram', 'unique'], isEssential: false,
    },
    {
      id: 'tokyo-5', name: 'Akihabara Electric Town', type: 'shopping', category: 'shopping',
      description: 'Tokyo\'s famous electronics and anime district — a haven for tech and otaku culture.',
      address: 'Akihabara, Chiyoda City, Tokyo',
      lat: 35.7022, lng: 139.7741, durationMin: 120, distanceFromPrevKm: 2.8, travelTimeMin: 15,
      rating: 4.4, reviewCount: 89234, photos: [], openingHours: '10:00 AM - 8:00 PM',
      priceLevel: 1, requiresBooking: false,
      bookingPlatforms: [], tags: ['anime', 'electronics', 'gaming', 'pop culture'], isEssential: false,
    },
    {
      id: 'tokyo-6', name: 'Ramen Nagi', type: 'restaurant', category: 'food',
      description: 'Award-winning ramen shop famous for its rich, customizable broth and handmade noodles.',
      address: '1 Chome-1-10 Nishishinjuku, Shinjuku City, Tokyo',
      lat: 35.6900, lng: 139.6994, durationMin: 45, distanceFromPrevKm: 3.5, travelTimeMin: 20,
      rating: 4.6, reviewCount: 23450, photos: [], openingHours: '11:00 AM - 10:00 PM',
      priceLevel: 1, requiresBooking: false,
      bookingPlatforms: [BOOKING_PLATFORMS.yelp], tags: ['ramen', 'japanese', 'noodles', 'local favourite'], isEssential: false,
    },
  ],

  'Bangkok': [
    {
      id: 'bkk-1', name: 'Grand Palace & Wat Phra Kaew', type: 'historical', category: 'culture',
      description: 'The dazzling complex of the former Royal Palace, home to the sacred Emerald Buddha.',
      address: 'Na Phra Lan Rd, Phra Nakhon, Bangkok',
      lat: 13.7500, lng: 100.4913, durationMin: 150, distanceFromPrevKm: 0, travelTimeMin: 0,
      rating: 4.6, reviewCount: 143210, photos: [], openingHours: '8:30 AM - 3:30 PM',
      priceLevel: 2, requiresBooking: false,
      bookingPlatforms: [BOOKING_PLATFORMS.klook, BOOKING_PLATFORMS.getyourguide], tags: ['royal', 'temple', 'cultural', 'landmark'], isEssential: false,
    },
    {
      id: 'bkk-2', name: 'Chatuchak Weekend Market', type: 'shopping', category: 'shopping',
      description: 'One of the world\'s largest outdoor markets with over 8,000 stalls of everything imaginable.',
      address: 'Kamphaeng Phet 2 Rd, Chatuchak, Bangkok',
      lat: 13.7999, lng: 100.5500, durationMin: 180, distanceFromPrevKm: 9.2, travelTimeMin: 35,
      rating: 4.5, reviewCount: 98321, photos: [], openingHours: 'Sat-Sun 9:00 AM - 6:00 PM',
      priceLevel: 1, requiresBooking: false,
      bookingPlatforms: [], tags: ['market', 'shopping', 'local', 'weekend'], isEssential: false,
    },
    {
      id: 'bkk-3', name: 'Pad Thai at Thip Samai', type: 'restaurant', category: 'food',
      description: 'Bangkok\'s most famous Pad Thai restaurant, operating since 1966. Lines out the door!',
      address: '313 Maha Chai Rd, Samran Rat, Phra Nakhon, Bangkok',
      lat: 13.7526, lng: 100.5041, durationMin: 45, distanceFromPrevKm: 1.1, travelTimeMin: 7,
      rating: 4.7, reviewCount: 34215, photos: [], openingHours: '5:00 PM - 1:00 AM',
      priceLevel: 1, requiresBooking: false,
      bookingPlatforms: [BOOKING_PLATFORMS.klook], tags: ['pad thai', 'thai food', 'street food', 'iconic'], isEssential: false,
    },
  ],
};

// Generic fallback places for any city
export const GENERIC_PLACES: Partial<Activity>[] = [
  { name: 'City Main Square', type: 'attraction', category: 'tourist', durationMin: 45, priceLevel: 0, requiresBooking: false, bookingPlatforms: [], tags: ['central', 'free', 'landmark'] },
  { name: 'Local History Museum', type: 'museum', category: 'culture', durationMin: 120, priceLevel: 1, requiresBooking: false, bookingPlatforms: [BOOKING_PLATFORMS.getyourguide], tags: ['history', 'culture', 'local'] },
  { name: 'Old Town Walking Tour', type: 'attraction', category: 'tourist', durationMin: 90, priceLevel: 1, requiresBooking: true, bookingPlatforms: [BOOKING_PLATFORMS.getyourguide, BOOKING_PLATFORMS.viator], tags: ['walking', 'historic', 'guided'] },
  { name: 'Local Food Market', type: 'attraction', category: 'food', durationMin: 60, priceLevel: 1, requiresBooking: false, bookingPlatforms: [], tags: ['food', 'local', 'market'] },
  { name: 'Rooftop Restaurant', type: 'restaurant', category: 'food', durationMin: 90, priceLevel: 3, requiresBooking: true, bookingPlatforms: [BOOKING_PLATFORMS.opentable, BOOKING_PLATFORMS.resy], tags: ['views', 'dining', 'upscale'] },
  { name: 'Street Art District', type: 'attraction', category: 'culture', durationMin: 60, priceLevel: 0, requiresBooking: false, bookingPlatforms: [], tags: ['art', 'photography', 'free'] },
  { name: 'City Park & Gardens', type: 'park', category: 'outdoor', durationMin: 60, priceLevel: 0, requiresBooking: false, bookingPlatforms: [], tags: ['nature', 'relax', 'free'] },
  { name: 'Shopping District', type: 'shopping', category: 'shopping', durationMin: 120, priceLevel: 2, requiresBooking: false, bookingPlatforms: [], tags: ['shopping', 'fashion', 'local brands'] },
  { name: 'Craft Beer Bar', type: 'bar', category: 'nightlife', durationMin: 90, priceLevel: 2, requiresBooking: false, bookingPlatforms: [], tags: ['drinks', 'local', 'craft beer'] },
  { name: 'Scenic Viewpoint', type: 'attraction', category: 'tourist', durationMin: 45, priceLevel: 0, requiresBooking: false, bookingPlatforms: [], tags: ['views', 'photography', 'free'] },
];

export const THEME_LABELS: Record<string, { name: string; emoji: string; color: string; description: string }> = {
  classic_tourist: { name: 'Classic Tourist', emoji: '🏛️', color: 'from-blue-500 to-purple-600', description: 'Iconic landmarks & must-see attractions' },
  culture_art: { name: 'Culture & Art', emoji: '🎨', color: 'from-purple-500 to-pink-600', description: 'Museums, galleries & historical gems' },
  foodie: { name: "Foodie's Paradise", emoji: '🍜', color: 'from-orange-500 to-red-600', description: 'Restaurants, cafés & food markets' },
  local_life: { name: 'Local Life', emoji: '🌿', color: 'from-green-500 to-teal-600', description: 'Hidden gems & neighbourhood vibes' },
  adventure_nightlife: { name: 'Adventure & Night', emoji: '🌙', color: 'from-indigo-500 to-violet-700', description: 'Entertainment, bars & nightlife' },
};
